-- Generated by matugen -- do not edit by hand.
-- Material You palette derived from the current wallpaper.
-- Applied as accent overlays on top of tokyonight by
-- dotfiles/dot_config/nvim/lua/plugins/colorscheme.lua.

return {
  primary = "{{colors.primary.default.hex}}",
  on_primary = "{{colors.on_primary.default.hex}}",
  primary_container = "{{colors.primary_container.default.hex}}",
  on_primary_container = "{{colors.on_primary_container.default.hex}}",
  secondary_container = "{{colors.secondary_container.default.hex}}",
  on_secondary_container = "{{colors.on_secondary_container.default.hex}}",
  tertiary = "{{colors.tertiary.default.hex}}",
  tertiary_container = "{{colors.tertiary_container.default.hex}}",
  on_tertiary_container = "{{colors.on_tertiary_container.default.hex}}",
  error = "{{colors.error.default.hex}}",
  outline = "{{colors.outline.default.hex}}",
  surface_container_high = "{{colors.surface_container_high.default.hex}}",
}
