source = ~/.config/hypr/colors.conf

general {
    disable_loading_bar = false
    grace = 3
    hide_cursor = true
    no_fade_in = true
}

background {
    path = screenshot
}

input-field {
    size = 300, 50
    outline_thickness = 3
    outer_color = $lock_input_color
    inner_color = $lock_background_color
    font_color = $lock_text_color
    placeholder_text = Password
    fade_on_empty = false
}
