legacy_layout = false
fps_only = true
fps_color_change = true
frametime = false
toggle_hud_position = Shift_L+F10
background_alpha = 0.0
position = top-right
fps_value = 30,60,144
fps_color = b22222,fdfd09,39f900
font_size = 14
mangoapp_steam = false
show_fps_limit = true
hud_compact = true
